package dev.abps.dungeon.mob;

import java.util.LinkedHashMap;
import java.util.Map;

/** Hitbox sizes and flags of the dungeon monsters. Generated by tools/gen_mob_models.py from tools/mob_specs.txt. */
public final class MobSpecs {

    public record Spec(String id, float width, float height, boolean flies) {
    }

    public static final Map<String, Spec> ALL = new LinkedHashMap<>();

    private static void add(String id, float width, float height, boolean flies) {
        ALL.put(id, new Spec(id, width, height, flies));
    }

    static {
        add("grave_knight", 1.00f, 2.08f, false);
        add("bone_caller", 1.10f, 2.14f, false);
        add("ghoul", 1.08f, 1.54f, false);
        add("crypt_weaver", 1.20f, 0.73f, false);
        add("frost_wraith", 0.83f, 2.45f, true);
        add("ice_brute", 1.38f, 2.15f, false);
        add("frost_sprite", 0.80f, 0.89f, true);
        add("magma_brute", 0.90f, 2.04f, false);
        add("ember_imp", 1.10f, 1.89f, true);
        add("forge_warden", 1.10f, 2.02f, false);
        add("sculk_lurker", 0.86f, 2.09f, false);
        add("echo_witch", 1.00f, 2.39f, false);
        add("shade", 0.48f, 1.37f, true);
        add("hollow_king", 1.33f, 2.43f, false);
        add("glacial_warden", 1.31f, 2.32f, false);
        add("infernal_colossus", 2.60f, 3.57f, false);
    }

    private MobSpecs() {
    }
}
