package dev.abps.content;

import dev.abps.AbpsMod;
import net.fabricmc.fabric.api.biome.v1.BiomeModifications;
import net.fabricmc.fabric.api.biome.v1.BiomeSelectors;
import net.fabricmc.fabric.api.loot.v3.LootTableEvents;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.tags.TagKey;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.item.AxeItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.HoeItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ShovelItem;
import net.minecraft.world.item.ToolMaterial;
import net.minecraft.world.item.equipment.ArmorMaterial;
import net.minecraft.world.item.equipment.ArmorType;
import net.minecraft.world.item.equipment.EquipmentAsset;
import net.minecraft.world.level.biome.Biomes;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.levelgen.GenerationStep;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;
import net.minecraft.world.level.storage.loot.BuiltInLootTables;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.entries.EmptyLootItem;
import net.minecraft.world.level.storage.loot.entries.LootItem;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Real registered content: the Ruby and Endite tiers. Ruby sits between diamond and netherite (and is now needed to
 * mine ancient debris); endite sits above netherite and is only found in the End's outer islands.
 *
 * Textures, models, recipes, loot tables, tags and worldgen features are generated by tools/gen_ores.py.
 */
public final class ModContent {

    private ModContent() {
    }

    /** Every item this registers, in creative-tab order. */
    public static final List<Item> ITEMS = new ArrayList<>();

    private static TagKey<net.minecraft.world.level.block.Block> blockTag(String name) {
        return TagKey.create(Registries.BLOCK, AbpsMod.id(name));
    }

    private static TagKey<Item> itemTag(String name) {
        return TagKey.create(Registries.ITEM, AbpsMod.id(name));
    }

    // ------------------------------------------------------------------ materials

    public static final ToolMaterial RUBY_TOOLS = new ToolMaterial(blockTag("incorrect_for_ruby_tool"), 1850, 8.5f, 3.5f, 18, itemTag("ruby_tool_materials"));
    public static final ToolMaterial ENDITE_TOOLS = new ToolMaterial(blockTag("incorrect_for_endite_tool"), 2750, 11f, 5.5f, 16, itemTag("endite_tool_materials"));

    private static ResourceKey<EquipmentAsset> asset(String name) {
        ResourceKey<? extends Registry<EquipmentAsset>> root = ResourceKey.createRegistryKey(Identifier.fromNamespaceAndPath("minecraft", "equipment_asset"));
        return ResourceKey.create(root, AbpsMod.id(name));
    }

    private static Map<ArmorType, Integer> defense(int boots, int legs, int chest, int helmet, int body) {
        Map<ArmorType, Integer> m = new EnumMap<>(ArmorType.class);
        m.put(ArmorType.BOOTS, boots);
        m.put(ArmorType.LEGGINGS, legs);
        m.put(ArmorType.CHESTPLATE, chest);
        m.put(ArmorType.HELMET, helmet);
        m.put(ArmorType.BODY, body);
        return m;
    }

    public static final ArmorMaterial RUBY_ARMOR = new ArmorMaterial(35, defense(3, 6, 8, 3, 11), 18, SoundEvents.ARMOR_EQUIP_DIAMOND, 2.5f, 0f,
            itemTag("repairs_ruby_armor"), asset("ruby"));
    public static final ArmorMaterial ENDITE_ARMOR = new ArmorMaterial(45, defense(3, 6, 9, 4, 13), 16, SoundEvents.ARMOR_EQUIP_NETHERITE, 4f, 0.15f,
            itemTag("repairs_endite_armor"), asset("endite"));

    // ------------------------------------------------------------------ registration helpers

    private static ResourceKey<Block> blockKey(String name) {
        return ResourceKey.create(Registries.BLOCK, AbpsMod.id(name));
    }

    private static ResourceKey<Item> itemKey(String name) {
        return ResourceKey.create(Registries.ITEM, AbpsMod.id(name));
    }

    private static Block block(String name, Function<BlockBehaviour.Properties, Block> factory, BlockBehaviour.Properties props, boolean fireproofItem) {
        ResourceKey<Block> key = blockKey(name);
        Block b = Registry.register(BuiltInRegistries.BLOCK, key, factory.apply(props.setId(key)));
        Item.Properties ip = new Item.Properties().setId(itemKey(name)).useBlockDescriptionPrefix();
        if (fireproofItem) ip = ip.fireResistant();
        ITEMS.add(Registry.register(BuiltInRegistries.ITEM, itemKey(name), new BlockItem(b, ip)));
        return b;
    }

    private static Item item(String name, Function<Item.Properties, Item> factory, boolean fireproof) {
        Item.Properties p = new Item.Properties().setId(itemKey(name));
        if (fireproof) p = p.fireResistant();
        Item i = Registry.register(BuiltInRegistries.ITEM, itemKey(name), factory.apply(p));
        ITEMS.add(i);
        return i;
    }

    // ------------------------------------------------------------------ content

    public static Block RUBY_ORE, DEEPSLATE_RUBY_ORE, RUBY_BLOCK, RUBY_BRICKS, RUBY_BRICK_STAIRS, RUBY_BRICK_SLAB, RUBY_LAMP;
    public static Block ENDITE_ORE, ENDITE_BLOCK, ENDITE_PLATING, ENDITE_PLATING_STAIRS, ENDITE_PLATING_SLAB;
    public static Item RUBY, ENDITE_SHARD, ENDITE_INGOT, ENDITE_TEMPLATE;
    public static Item RUBY_SWORD, RUBY_PICKAXE, RUBY_AXE, RUBY_SHOVEL, RUBY_HOE, RUBY_HELMET, RUBY_CHESTPLATE, RUBY_LEGGINGS, RUBY_BOOTS;
    public static Item ENDITE_SWORD, ENDITE_PICKAXE, ENDITE_AXE, ENDITE_SHOVEL, ENDITE_HOE, ENDITE_HELMET, ENDITE_CHESTPLATE, ENDITE_LEGGINGS, ENDITE_BOOTS;

    public static void register() {
        // Ruby
        RUBY = item("ruby", Item::new, false);
        RUBY_ORE = block("ruby_ore", p -> new DropExperienceBlock(UniformInt.of(3, 7), p), BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_ORE), false);
        DEEPSLATE_RUBY_ORE = block("deepslate_ruby_ore", p -> new DropExperienceBlock(UniformInt.of(3, 7), p),
                BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_DIAMOND_ORE), false);
        RUBY_BLOCK = block("ruby_block", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.DIAMOND_BLOCK), false);
        RUBY_BRICKS = block("ruby_bricks", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.STONE_BRICKS).strength(3f, 6f), false);
        Block bricks = RUBY_BRICKS;
        RUBY_BRICK_STAIRS = block("ruby_brick_stairs", p -> new StairBlock(bricks.defaultBlockState(), p), BlockBehaviour.Properties.ofFullCopy(bricks), false);
        RUBY_BRICK_SLAB = block("ruby_brick_slab", SlabBlock::new, BlockBehaviour.Properties.ofFullCopy(bricks), false);
        RUBY_LAMP = block("ruby_lamp", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.GLOWSTONE).strength(1.5f), false);
        RUBY_SWORD = item("ruby_sword", p -> new Item(p.sword(RUBY_TOOLS, 3f, -2.4f)), false);
        RUBY_PICKAXE = item("ruby_pickaxe", p -> new Item(p.pickaxe(RUBY_TOOLS, 1f, -2.8f)), false);
        RUBY_AXE = item("ruby_axe", p -> new AxeItem(RUBY_TOOLS, 5f, -3f, p), false);
        RUBY_SHOVEL = item("ruby_shovel", p -> new ShovelItem(RUBY_TOOLS, 1.5f, -3f, p), false);
        RUBY_HOE = item("ruby_hoe", p -> new HoeItem(RUBY_TOOLS, -3.5f, 0f, p), false);
        RUBY_HELMET = item("ruby_helmet", p -> new Item(p.humanoidArmor(RUBY_ARMOR, ArmorType.HELMET)), false);
        RUBY_CHESTPLATE = item("ruby_chestplate", p -> new Item(p.humanoidArmor(RUBY_ARMOR, ArmorType.CHESTPLATE)), false);
        RUBY_LEGGINGS = item("ruby_leggings", p -> new Item(p.humanoidArmor(RUBY_ARMOR, ArmorType.LEGGINGS)), false);
        RUBY_BOOTS = item("ruby_boots", p -> new Item(p.humanoidArmor(RUBY_ARMOR, ArmorType.BOOTS)), false);

        // Endite
        ENDITE_SHARD = item("endite_shard", Item::new, true);
        ENDITE_INGOT = item("endite_ingot", Item::new, true);
        ENDITE_TEMPLATE = item("endite_upgrade_smithing_template", Item::new, true);
        ENDITE_ORE = block("endite_ore", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.ANCIENT_DEBRIS), true);
        ENDITE_BLOCK = block("endite_block", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.NETHERITE_BLOCK), true);
        ENDITE_PLATING = block("endite_plating", Block::new, BlockBehaviour.Properties.ofFullCopy(Blocks.POLISHED_BLACKSTONE_BRICKS).strength(5f, 12f), true);
        Block plating = ENDITE_PLATING;
        ENDITE_PLATING_STAIRS = block("endite_plating_stairs", p -> new StairBlock(plating.defaultBlockState(), p), BlockBehaviour.Properties.ofFullCopy(plating), true);
        ENDITE_PLATING_SLAB = block("endite_plating_slab", SlabBlock::new, BlockBehaviour.Properties.ofFullCopy(plating), true);
        ENDITE_SWORD = item("endite_sword", p -> new Item(p.sword(ENDITE_TOOLS, 3f, -2.4f)), true);
        ENDITE_PICKAXE = item("endite_pickaxe", p -> new Item(p.pickaxe(ENDITE_TOOLS, 1f, -2.8f)), true);
        ENDITE_AXE = item("endite_axe", p -> new AxeItem(ENDITE_TOOLS, 5f, -3f, p), true);
        ENDITE_SHOVEL = item("endite_shovel", p -> new ShovelItem(ENDITE_TOOLS, 1.5f, -3f, p), true);
        ENDITE_HOE = item("endite_hoe", p -> new HoeItem(ENDITE_TOOLS, -5.5f, 0f, p), true);
        ENDITE_HELMET = item("endite_helmet", p -> new Item(p.humanoidArmor(ENDITE_ARMOR, ArmorType.HELMET)), true);
        ENDITE_CHESTPLATE = item("endite_chestplate", p -> new Item(p.humanoidArmor(ENDITE_ARMOR, ArmorType.CHESTPLATE)), true);
        ENDITE_LEGGINGS = item("endite_leggings", p -> new Item(p.humanoidArmor(ENDITE_ARMOR, ArmorType.LEGGINGS)), true);
        ENDITE_BOOTS = item("endite_boots", p -> new Item(p.humanoidArmor(ENDITE_ARMOR, ArmorType.BOOTS)), true);

        worldgen();
        loot();
    }

    /** Ruby ore deep in the overworld; endite ore in the End's outer islands (never on the dragon's island). */
    private static void worldgen() {
        BiomeModifications.addFeature(BiomeSelectors.foundInOverworld(), GenerationStep.Decoration.UNDERGROUND_ORES,
                ResourceKey.create(Registries.PLACED_FEATURE, AbpsMod.id("ore_ruby")));
        BiomeModifications.addFeature(BiomeSelectors.foundInTheEnd().and(BiomeSelectors.excludeByKey(Biomes.THE_END)),
                GenerationStep.Decoration.UNDERGROUND_ORES, ResourceKey.create(Registries.PLACED_FEATURE, AbpsMod.id("ore_endite")));
    }

    /** The endite upgrade template turns up in End City treasure, about one chest in four. */
    private static void loot() {
        LootTableEvents.MODIFY.register((key, tableBuilder, source, provider) -> {
            if (!source.isBuiltin() || !BuiltInLootTables.END_CITY_TREASURE.equals(key)) return;
            tableBuilder.withPool(LootPool.lootPool()
                    .add(LootItem.lootTableItem(ENDITE_TEMPLATE).setWeight(1))
                    .add(EmptyLootItem.emptyItem().setWeight(3)));
        });
    }

    @SuppressWarnings("unused")
    private static final Class<?> KEEP = PlacedFeature.class;
}
